CREATE TABLE IF NOT EXISTS numbers
(
    number   INT PRIMARY KEY,
    trivia   CHARACTER VARYING(30) NOT NULL,
    math     CHARACTER VARYING(30) NOT NULL,
    year     CHARACTER VARYING(30) NOT NULL
);